#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Wed Jul 22 11:06:28 CST 2026
maven-metadata-aliyun-springai.xml.error=Could not transfer metadata com.google.protobuf\:protobuf-java/maven-metadata.xml from/to aliyun-springai (https\://maven.aliyun.com/repository/springai)\: status code\: 401, reason phrase\: Unauthorized (401)
maven-metadata-aliyun-springai.xml/@default-aliyun-springai-https\://maven.aliyun.com/repository/springai/.lastUpdated=1784689588626
maven-metadata-central.xml.lastUpdated=1784689588627
maven-metadata-spring-milestones.xml.error=
maven-metadata-spring-milestones.xml.lastUpdated=1784689588627
